YumYum/urls.py
"""YumYum URL Configuration"""
from django.conf.urls import url
from django.contrib import admin
from recipes.views import RecipeView, RecommendedRecipeView, RecipeDetailView, search_recipe

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recipes/$', RecipeView.as_view(), name="recipes"),
    url(r'^search/$', search_recipe, name="search_recipes"),
    url(r'^recommended/$', RecommendedRecipeView.as_view(), name="recommended"),
    url(r'^recommended/(?P<pk>\w+)/$', RecipeDetailView.as_view(), name="detail"),
]

recipes/models.py
from django.db import models


class Recipe(models.Model):
    CUISINE = (
        ('brak', 'brak'),
        ('angielska', 'angielska'),
        ('polska', 'polska'),
        ('francuska', 'francuska'),
        ('wloska', 'wloska'),
        ('azjatycka', 'azjatycka')
    )
    DIET_TYPE = (
        ('weganska', 'weganska'),
        ('wegetarianska', 'wegetarianska'),
        ('bez glutenu', 'bez glutenu'),
        ('bez laktozy', 'bez laktozy'),
        ('brak', 'brak')
    )
    DIFFICULTY_LEVEL = (
        ('latwy', 'latwy'),
        ('sredni', 'sredni'),
        ('trudny', 'trudny')
    )
    MEAL_TYPE = (
        ('sniadanie', 'sniadanie'),
        ('obiad', 'obiad'),
        ('przekąska', 'przekąska'),
        ('kolacja', 'kolacja'),
        ('deser', 'deser')
    )

    id = models.IntegerField(primary_key=True, null=False)
    name = models.CharField(max_length=1000, null=False)
    diet_type = models.CharField(max_length=20, choices=DIET_TYPE, default='brak')
    cuisine = models.CharField(max_length=20, choices=CUISINE, default='brak')
    difficulty_level = models.CharField(max_length=20, choices=DIFFICULTY_LEVEL, default='sredni')
    meal_type = models.CharField(max_length=20, choices=MEAL_TYPE)
    ingredients = models.CharField(max_length=1000, null=False)
    prepare_time = models.IntegerField(default=0)
    calorie = models.IntegerField(default=0)
    cost = models.IntegerField(default=0)
    description = models.CharField(max_length=100000, null=False, default=None)


    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        ordering = ['name']

recipes/forms.py
from django import forms


class SearchRecipeForm(forms.Form):
    CUISINE = (('brak', 'brak'),
               ('angielska', 'angielska'),
               ('polska', 'polska'),
               ('francuska', 'francuska'),
               ('wloska', 'wloska'),
               ('azjatycka', 'azjatycka')
               )
    DIET_TYPE = (('brak', 'brak'),
                 ('weganska', 'weganska'),
                 ('wegetarianska', 'wegetarianska'),
                 ('bez glutenu', 'bez glutenu'),
                 ('bez laktozy', 'bez laktozy')
                 )
    DIFFICULTY_LEVEL = (('brak', 'brak'),
                        ('latwy', 'latwy'),
                        ('sredni', 'sredni'),
                        ('trudny', 'trudny')
                        )
    MEAL_TYPE = (('brak', 'brak'),
                 ('sniadanie', 'sniadanie'),
                 ('obiad', 'obiad'),
                 ('przekąska', 'przekąska'),
                 ('kolacja', 'kolacja'),
                 ('deser', 'deser')
                 )
    diet_type = forms.ChoiceField(choices=DIET_TYPE, required=False, label='Rodzaj diety')
    cuisine = forms.ChoiceField(choices=CUISINE, required=False, label='Rodzaj kuchni')
    difficulty_level = forms.ChoiceField(choices=DIFFICULTY_LEVEL, required=False, label='Poziom trudności')
    meal_type = forms.ChoiceField(choices=MEAL_TYPE, required=False, label='Rodzaj posiłku')
    allergens = forms.CharField(required=False, label='Alergeny', initial='brak')
    products = forms.CharField(required=False, label='Produkty, które mamy w kuchni', initial='brak')
    prepare_time = forms.IntegerField(required=False, label='Czas przygotowania [min]', initial=100)
    calorie = forms.IntegerField(required=False, label='Ilość kalorii', initial=1000)
    cost = forms.IntegerField(required=False, label='Koszt przygotowania posiłku [zł]', initial=100)
    cost_kcal = forms.IntegerField(required=False, label='Koszt czy ilość kalorii?', initial=1)
    cost_time = forms.IntegerField(required=False, label='Koszt czy czas przygotowania posiłku?', initial=1)
    kcal_time = forms.IntegerField(required=False, label='Ilość kalorii czy czas przygotowania posiłku?', initial=1)
    veto_time = forms.IntegerField(required=False, label='Czas przygotowania posiłku', initial=10)
    veto_cost = forms.IntegerField(required=False, label='Koszt', initial=10)
    veto_kcal = forms.IntegerField(required=False, label='Ilość kalorii', initial=200)

recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .electra import get_sorted_recipes, electre_I_method, electre_III_method
from .models import Recipe
from .forms import SearchRecipeForm


class RecipeView(ListView):
    model = Recipe
    template_name = 'recipes/recipes.html'


class RecommendedRecipeView(ListView):
    template_name = 'recipes/recommended_recipes.html'


class RecipeDetailView(DetailView):
    queryset = Recipe.objects.all()

    def get_context_data(self, **kwargs):
        context = super(RecipeDetailView, self).get_context_data(**kwargs)
        return context


def search_recipe(request):
    if request.method == 'POST':
        form = SearchRecipeForm(request.POST)
        if form.is_valid():
            user_choices = {'diet type': form.data['diet_type'], 'cuisine': form.data['cuisine'],
                            'difficulty level': form.data['difficulty_level'],
                            'meal type': form.data['meal_type'], 'allergens': form.data['allergens'],
                            'prepare_time': form.data['prepare_time'], 'calorie': form.data['calorie'],
                            'cost': form.data['cost'], 'products': form.data['products'],
                            'cost_kcal': form.data['cost_kcal'], 'cost_time': form.data['cost_time'],
                            'kcal_time': form.data['kcal_time'], 'veto_time': form.data['veto_time'],
                            'veto_cost': form.data['veto_cost'], 'veto_kcal': form.data['veto_kcal']}
            recipes = get_sorted_recipes(user_choices, electre_III_method)
            template_name = 'recipes/recommended_recipes.html'
            return render(request, template_name, {'recipes': recipes})
    else:
        form = SearchRecipeForm()
    return render(request, 'recipes/search_recipe.html', {'form': form})

recipes/templates/recipes/base.html
<html>
<head>
    <style>
div {
    margin: 85px 260px 5px 280px;
}


    </style>
    <title>Yum Yum</title>

</head>
<body style="background: url(http://www.evelynsmark.com/wp-content/uploads/2017/03/Evelyns-Mark-Raw-Vegan-Recipes-Background.jpg); background-size: 100%;">
<div class="page-header">
    <h1>Yum Yum</h1>
    <b><a href="/recipes/">Przepisy</a>
        <a href="/search/">Wyszukaj</a> </b>

</div>

{% block content %}
{% endblock %}

</body>
</html>

recipes/templates/recipes/recipe_detail.html
{% extends 'recipes/base.html' %}

{% block content %}

<div class="row">
    <h2>{{ object.name }}</h2>
    <p><b>Rodzaj kuchni:</b> {{ object.cuisine }}</p>
    <p><b>Rodzaj posiłku:</b>  {{ object.meal_type }}</p>
    <p><b>Rodzaj diety:</b>  {{ object.diet_type }}</p>
    <p><b>Poziom trudności:</b>  {{ object.difficulty_level }}</p>
    <p><b>Ilość kalorii:</b>  {{ object.calorie }}</p>
    <p><b>Składniki:</b>  {{ object.ingredients }}</p>
    <p><b>Czas przygotowania:</b>  {{ object.prepare_time }}</p>
    <p><b>Kosz dokupienia składników:</b>  {{ object.cost }}</p>
    <p><b>Opis:</b></p>
    <p>{{ object.description }}</p>
</div>

{% endblock %}

recipes/templates/recipes/recipes.html
{% extends 'recipes/base.html' %}

{% block content %}
<style>
        table, th, td {
        border: 1px solid black;
        padding: 3px;
        border-collapse: collapse;
        text-align: center;
        }
        h2 {text-align: center;
        }


</style>
<div class="row">
    <h2>Wszystkie przepisy</h2>

    <table style="width:100%">
        <tr>
            <th>Id</th>
            <th>Nazwa</th>
            <th>Rodzaj diety</th>
            <th>Rodzaj kuchni</th>
            <th>Poziom trudności</th>
            <th>Rodzaj posiłku</th>
            <th>Składniki</th>
            <th>Czas przygotowania</th>
            <th>Ilość kalorii</th>
            <th>Koszt przygotowania</th>
        </tr>
        {% for obj in recipe_list %}
        <tr>
            <td>{{obj.id}}</td>
            <td>{{obj.name}}</td>
            <td> {{obj.diet_type}}</td>
            <td> {{obj.cuisine}}</td>
            <td>{{obj.difficulty_level}}</td>
            <td> {{obj.meal_type}}</td>
            <td> {{obj.ingredients}}</td>
            <td>{{obj.prepare_time}}</td>
            <td> {{obj.calorie}}</td>
            <td> {{obj.cost}}</td>
        </tr>
        {% endfor %}

    </table>
</div>

{% endblock %}

recipes/templates/recipes/recommended_recipes.html
{% extends 'recipes/base.html' %}

{% block content %}
<style>
        table, th, td {
        border: 1px solid black;
        padding: 3px;
        border-collapse: collapse;
        text-align: center;
        }
        h2 {text-align: center;
        }



</style>
<div class="row">
    <h2>Przepisy dla Ciebie</h2>

    <table style="width:100%">

        <tr>
            <th>Nazwa</th>
            <th>Koszt</th>
            <th>Kalorie</th>
            <th>Czas przygotowania</th>
            <th>Stosunek najlepszego do pozostałych [%]</th>
        </tr>
        {% for obj in recipes %}
        <tr>
            <td><a href="/recommended/{{obj.id}}/">{{obj.name}}</a></td>
            <td>{{obj.cost}}</td>
            <td>{{obj.calorie}}</td>
            <td>{{obj.prepare_time}}</td>
            <td>{{obj.ratio}}</td>
        </tr>
        {% endfor %}

    </table>
</div>

{% endblock %}

recipes/templates/recipes/search_recipe.html
{% extends 'recipes/base.html' %}

{% block content %}

<div class="row">
    <h1>Szukaj przepisów</h1>

    <form method="POST"> {%csrf_token%}
        <p><b>Rodzaj kuchni:</b> {{ form.cuisine }}</p>
        <p><b>Rodzaj posiłku:</b> {{ form.meal_type }}</p>
        <p><b>Rodzaj diety:</b> {{ form.diet_type }}</p>
        <p><b>Poziom trudności:</b> {{ form.difficulty_level }}</p>
        <p><b>Ilość kalorii:</b> {{ form.calorie }}</p>
        <p><b>Alergeny:</b> {{ form.allergens }}</p>
        <p><b>Produkty, które mamy w lodówce:</b> {{ form.products }}</p>
        <p><b>Czas przygotowania:</b> {{ form.prepare_time }}</p>
        <p><b>Kosz dokupienia składników:</b> {{ form.cost }}</p>
        <h3>Co jest dla Ciebie ważniejsze ? </h3>
        <p>Wpisz wartości: 1- mniej ważne, 9- zdecydowanie ważniejsze </p>
        <p><b>Koszt czy ilość kalorii?</b> {{ form.cost_kcal }}</p>
        <p><b>Koszt czy czas przygotowania?</b> {{ form.cost_time }}</p>
        <p><b>Ilość kalorii czy czas przygotowania?</b> {{ form.kcal_time }}</p>
        <p></p>
        <h3>Jaka maksymalnie może być różnica pomiędzy wartościami kryteriów poszczególnych przepisów? </h3>
        <p><b>Koszt:</b> {{ form.veto_cost }}</p>
        <p><b>Czas przygotowania:</b> {{ form.veto_time }}</p>
        <p><b>Ilość kalorii:</b> {{ form.veto_kcal }}</p>
        <button type="submit">Szukaj</button>
    </form>
</div>

{% endblock %}